#!/bin/sh

OLD_EMAIL=$1
CORRECT_NAME=$2
CORRECT_EMAIL=$3

if [ -z "${OLD_EMAIL}" ] || [ -z "${CORRECT_NAME}" ] || [ -z "${CORRECT_EMAIL}" ]; then
  echo 'Missing some arguments'
  echo 'Usage: git-rewrite-author old@example.com" author@example.com author'
  exit 1
fi

ENV_FILTER='

if [ "$GIT_COMMITTER_EMAIL" = "'${OLD_EMAIL}'" ]
then
    export GIT_COMMITTER_NAME="'${CORRECT_NAME}'"
    export GIT_COMMITTER_EMAIL="'${CORRECT_EMAIL}'"
fi
if [ "$GIT_AUTHOR_EMAIL" = "'${OLD_EMAIL}'" ]
then
    export GIT_AUTHOR_NAME="'${CORRECT_NAME}'"
    export GIT_AUTHOR_EMAIL="'${CORRECT_EMAIL}'"
fi
'

git filter-branch --env-filter "${ENV_FILTER}" --tag-name-filter cat -- --branches --tags
